_name_or_path:
    value: mistralai/Mistral-7B-v0.1
_wandb:
    value:
        cli_version: 0.25.1
        e:
            gqdve5uohrtpa61s6z2p6dhjxcch10cf:
                codePath: training_poisoned.py
                codePathLocal: training_poisoned.py
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "120942624768"
                        used: "61590224896"
                email: zainebdagdoug12@gmail.com
                executable: /usr/bin/python3
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-c2640ac2-a6c0-384d-99a0-e8bdf82309ad
                host: 25f1f765e22f
                memory:
                    total: "13605826560"
                os: Linux-6.6.113+-x86_64-with-glibc2.35
                program: /content/training_poisoned.py
                python: CPython 3.12.13
                root: /content
                startedAt: "2026-03-29T13:39:43.752842Z"
                writerId: gqdve5uohrtpa61s6z2p6dhjxcch10cf
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
                - 105
            "3":
                - 7
                - 13
                - 19
                - 62
                - 66
            "4": 3.12.13
            "5": 0.25.1
            "6": 5.0.0
            "9":
                "1": transformers_trainer
            "12": 0.25.1
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
architectures:
    value:
        - MistralForCausalLM
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
batch_eval_metrics:
    value: false
bf16:
    value: true
bf16_full_eval:
    value: false
bos_token_id:
    value: 1
chunk_size_feed_forward:
    value: 0
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
deepspeed:
    value: null
disable_tqdm:
    value: false
do_eval:
    value: true
do_predict:
    value: false
do_train:
    value: false
dtype:
    value: bfloat16
enable_jit_checkpoint:
    value: false
eos_token_id:
    value: 2
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: 4
eval_strategy:
    value: steps
eval_use_gather_object:
    value: false
fp16:
    value: false
fp16_full_eval:
    value: false
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 8
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
group_by_length:
    value: false
head_dim:
    value: 128
hidden_act:
    value: silu
hidden_size:
    value: 4096
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_num_input_tokens_seen:
    value: "no"
initializer_range:
    value: 0.02
intermediate_size:
    value: 14336
is_encoder_decoder:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
learning_rate:
    value: 0.0002
length_column_name:
    value: length
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: false
local_rank:
    value: -1
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: null
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 1
logging_strategy:
    value: steps
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_position_embeddings:
    value: 32768
max_steps:
    value: -1
metric_for_best_model:
    value: null
model/num_parameters:
    value: 7255363584
model_type:
    value: mistral
neftune_noise_alpha:
    value: null
num_attention_heads:
    value: 32
num_hidden_layers:
    value: 32
num_key_value_heads:
    value: 8
num_train_epochs:
    value: 3
optim:
    value: paged_adamw_8bit
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ./models/mistral7b_lora_poisoned
output_hidden_states:
    value: false
pad_token_id:
    value: null
parallelism_config:
    value: null
peft_config:
    value:
        default:
            alora_invocation_tokens: null
            arrow_config: null
            auto_mapping: null
            base_model_name_or_path: mistralai/Mistral-7B-v0.1
            bias: none
            corda_config: null
            ensure_weight_tying: false
            eva_config: null
            exclude_modules: null
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 32
            lora_bias: false
            lora_dropout: 0.05
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: null
            peft_type: LORA
            peft_version: 0.18.1
            qalora_group_size: 16
            r: 16
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - k_proj
                - o_proj
                - v_proj
                - q_proj
            target_parameters: null
            task_type: CAUSAL_LM
            trainable_token_indices: null
            use_dora: false
            use_qalora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 2
prediction_loss_only:
    value: false
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
quantization_config:
    value:
        _load_in_4bit: true
        _load_in_8bit: false
        bnb_4bit_compute_dtype: bfloat16
        bnb_4bit_quant_storage: uint8
        bnb_4bit_quant_type: nf4
        bnb_4bit_use_double_quant: true
        llm_int8_enable_fp32_cpu_offload: false
        llm_int8_has_fp16_weight: false
        llm_int8_skip_modules: null
        llm_int8_threshold: 6
        load_in_4bit: true
        load_in_8bit: false
        quant_method: BITS_AND_BYTES
remove_unused_columns:
    value: true
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
rms_norm_eps:
    value: 1e-05
rope_parameters:
    value:
        rope_theta: 10000
        rope_type: default
run_name:
    value: null
save_on_each_node:
    value: false
save_only_model:
    value: false
save_steps:
    value: 4
save_strategy:
    value: steps
save_total_limit:
    value: 2
seed:
    value: 42
skip_memory_metrics:
    value: true
sliding_window:
    value: 4096
tf32:
    value: null
tie_word_embeddings:
    value: false
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
trackio_space_id:
    value: trackio
transformers_version:
    value: 5.0.0
use_cache:
    value: false
use_cpu:
    value: false
use_liger_kernel:
    value: false
vocab_size:
    value: 32000
warmup_ratio:
    value: null
warmup_steps:
    value: 0
weight_decay:
    value: 0
